### PR TITLE
Added all of ticket 2 functionality, can view employees

### PR DESCRIPTION
**Pull request by TheByteSizeDev**
Fixed:
Fixed connections import
updated template to include department instead of computer
updated views to include department join

### CODE REVIEW

**Comment by joekennerly** [comment]
we need to add "connections.py" (with an s) to the .gitignore

**Comment by bparker12** [comment]
please include the insert into statement, so we can populate an employee into the DB

**Comment by TheByteSizeDev** [comment]
Hey guys I put in the .gitignore that was sent out in the slack channel. 

#db location
hrapp/views/connection.py

**Comment by TheByteSizeDev** [comment]
Wait I see it now, my bad.

**Review by bparker12 — APPROVED** [review]
👍  Looks good!

**Review by BerkeleyPlatte — APPROVED** [review]
👍

**Pull request merged**
